//The Javascript code for this file is generated by running /mapsheet/compile_mapsheet.py and should be edited by editing /mapsheet/azimuthal_projection.svg with an SVG editor.

export declare function writeAllCountryNames(): void;
