//The Javascript code for this file is generated by running /mapsheet/compile_mapsheet.py and should be edited by editing /mapsheet/azimuthal_projection.svg with an SVG editor.

/**
 * The number of hexes from the left edge of the mapsheet to the right edge.
 */
export declare const mapWidth: number;

/**
 * The number of hexes from the top edge of the mapsheet to the bottom edge.
 */
export declare const mapHeight: number;

/**
 * The width of a hex in zoom-independent pixels.
 */
export declare const hexWidth: number;

/**
 * The height of a hex in zoom-independent pixels.
 */
export declare const hexHeight: number;

/**
 * The width of the mapsheet in zoom-independent pixels.
 */
export declare const svgWidth: number;

/**
 * The height of the mapsheet in zoom-independent pixels.
 */
export declare const svgHeight: number;

/**
 * Creates the Hex objects.
 */
export declare function createHexes(): void;
